# Generated by Django 5.1.7 on 2025-05-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('sales_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('surface', models.FloatField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='real_estates/')),
                ('reserved', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('agent', models.ManyToManyField(to='AgencyApp.agent')),
                ('characteristics', models.ManyToManyField(to='AgencyApp.characteristic')),
            ],
        ),
    ]
