# Generated by Django 5.1.7 on 2025-05-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0002_agent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
