# Generated by Django 5.1.7 on 2025-05-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0003_alter_realestate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
